# Generated by Django 5.1 on 2024-09-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruits',
            name='fruit_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fruits',
            name='fruit_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
