# Generated by Django 5.1 on 2024-09-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_fruits_fruit_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruits',
            name='fruit_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
