# Generated by Django 5.1 on 2024-09-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_fruits_fruit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruits',
            name='fruit_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
