# Generated by Django 5.1 on 2024-09-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_fruits_fruit_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruits',
            name='fruit_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fruits',
            name='fruit_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
