# Generated by Django 5.1 on 2024-09-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_alter_fruits_fruit_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruits',
            name='fruit_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
