# Generated by Django 5.1 on 2024-09-27 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_alter_fruits_fruit_qty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruits',
            options={'ordering': ['id']},
        ),
    ]
