# Generated by Django 5.1 on 2024-10-04 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_alter_fruits_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[(1, 'admin'), (2, 'user'), (3, 'viewer')], default=2)),
            ],
        ),
        migrations.AddField(
            model_name='fruits',
            name='fruit_createdBy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='activity.user'),
            preserve_default=False,
        ),
    ]
