# Generated by Django 5.1 on 2024-10-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_user_fruits_fruit_createdby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruits',
            name='fruit_createdBy',
        ),
    ]
