# Generated by Django 5.1 on 2024-10-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_remove_fruits_fruit_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'user'), (3, 'viewer')], default=2),
        ),
    ]
